name = "cloudflare_temp_email"
# 必须加上目录前缀，因为 GitHub Actions 在根目录运行
main = "worker/index.js" 
compatibility_date = "2024-04-03"

[[kv_namespaces]]
binding = "KV"
id = "875f916a4b7c4623940057763002e393KV_ID"

[vars]
# 这里的域名要换成你自己的
DOMAIN = "mail.yourdomain.com"
